### ISSUE TITLE
Add "generic objects" to tracking

### ISSUE THREAD

**Issue by Gregwar** [Rhoban/junior-ssl#13]
- [X] Aruco trackers 8 to 15 are recognized as objects in software
- [x] Provide an high-level API for those
- [ ] Provide a PDF and document the feature
